#!/bin/bash

remove_single_quote='s/'\''//g;'
remove_double_quote='s/\"//g;'
add_linestart='s/^/\"/;'
add_lineend='s/$/\",/;'
replace_equal='s/=/\":\"/;'
remove_last_comma='$s/.$//g;'

cat - | sed -e "$remove_single_quote $remove_double_quote $add_linestart $add_lineend $replace_equal" | sed -e "$remove_last_comma"

